stages:
  - test
  - publish

include:
  - component: $CI_SERVER_FQDN/ci-component/rust/test@main

publish:
  stage: publish
  image: rust:latest
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - cargo publish --registry kellnr --token ${KELLNR_ACCESS_TOKEN}
