stages:
  - test
  - publish

test:
  stage: test
  image: rust:latest
  tags:
    - docker
  script:
    - cargo test

publish:
  stage: publish
  image: rust:latest
  tags:
    - docker
  script:
    - cargo publish --registry kellnr --token ${KELLNR_ACCESS_TOKEN}
